version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m4tcg34r0j6x"
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=026314309370.dkr.ecr.us-east-1.amazonaws.com/samapp7427b055/helloworldfunction19d43fc4repo"]
